{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-ingress-nginx-controller
  labels:
    k8s-app: {{ template "name" . }}-ingress-nginx-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: {{ template "name" . }}-ingress-nginx-controller
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.7
        name: {{ .Chart.Name }}-ingress-nginx-controller
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/{{ template "fullname" . }}-ingress-default-http-backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ template "name" . }}-ingress-service
  name: {{ template "fullname" . }}-ingress-service
spec:
  ports:
    - port: {{ .Values.ingress.service.externalPort }}
      targetPort: 80
  selector:
    k8s-app: {{ template "name" . }}-ingress-nginx-controller
  type: {{ .Values.ingress.service.type }}
{{- end -}}
